version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
    - 80:80
    environment:
      DB_HOST: db
      DB_DATABASE: mymovie
      DB_USERNAME: root
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mymovie.sql:/docker-entrypoint-initdb.d/mymovie.sql